### PR TITLE
Parallelised SceneNode child bound computations.

### PR DESCRIPTION
**Pull request by johnhaddon**

### CODE REVIEW

**Comment by johnhaddon** [comment]
Yo, @andrewkaufman, would you like to comment on my half-assed branch?

**Comment by andrewkaufman** [comment]
Nah, its got conflicts. I ain't reviewing no conflicts.

**Comment by johnhaddon** [comment]
So, now you were mentioned earlier, do you receive additional comments that don't mention you?

**Comment by andrewkaufman** [comment]
I still got it :tada:

**Comment by johnhaddon** [comment]
Awesome. Let's give this a bash next time we need a bit of pre-PR discussion then...

**Pull request closed without merging**
